CREATE TABLE user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE user
    ADD CONSTRAINT uk_email UNIQUE (email);